org:
  zew:
    kafka:
      consumer:
        group: consumerGroup1
      topic:
        donations: donations
      max-poll: 1
      offset: earliest
      autocommit: false
      bootstrap-servers: localhost:9092
